### ISSUE TITLE
smod.modelFitGrid

### ISSUE THREAD

**Issue by carolinaherrera** [aburgasser/splat#100]
INPUT:
p = smod.modelFitGrid(sp[0],teff_range=[1200,2500])

ERROR:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-119-a4e86fbc958e> in <module>()
----> 1 p = smod.modelFitGrid(sp[0],teff_range=[1200,2500])

/Users/carolinaherrera/splat/splat/model.py in modelFitGrid(spec, **kwargs)
   1210             print('\t{} = {} {}'.format(SPECTRAL_MODEL_PARAMETERS[ms]['title'],parameters[0][ms],SPECTRAL_MODEL_PARAMETERS[ms]['unit']))
   1211         if compute_radius == True:
-> 1212             print('\tRadius = {} {}'.format(parameters[0]['radius'].value,parameters[0]['radius'].unit))
   1213         print('\tchi={}'.format(stats[0]))
   1214 

AttributeError: 'float' object has no attribute 'value'

**Comment by aburgasser** [comment]
squashed!
