### ISSUE TITLE
issue with database search

### ISSUE THREAD

**Issue by chihchunhsu** [aburgasser/splat#101]
`splist = splat.getSpectrum(spt=[20,25],jmag=[14.,20.])`

returns 

/Users/dinohsu/Desktop/splat/splat/core.pyc in searchLibrary(*args, **kwargs)
   2157         if not isinstance(mag,list):        # one value = faint limit
   2158             mag = [0,mag]
-> 2159         source_db['JMAGN'] = [float('0'+x) for x in numpy.ma.filled(source_db['J_2MASS'],'')]
   2160         source_db['SELECT'][numpy.logical_and(source_db['JMAGN'] >= mag[0],source_db['JMAGN'] <= mag[1])] += 1
   2161         count+=1.

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

**Comment by aburgasser** [comment]
residual issue with conversion to pandas - now fixed
