### ISSUE TITLE
error in modelFitMCMC

### ISSUE THREAD

**Issue by carolinaherrera** [aburgasser/splat#102]
Input:    smod.modelFitMCMC(sp[0],nsamples=15000)

Error:
ValueError                                Traceback (most recent call last)
<ipython-input-209-28d9944bfd9c> in <module>()
----> 1 smod.modelFitMCMC(sp[0],nsamples=15000)

/Users/carolinaherrera/splat/splat/model.py in modelFitMCMC(spec, **kwargs)
   1514             dp['weights'] = [1.-stats.f.cdf(c/numpy.nanmin(chisqrs), eff_dof, eff_dof) for c in chisqrs]
   1515             dp.to_csv(output_parameters,index=False)
-> 1516             _modelFitMCMC_plotChains(dp,columns=param_plot,burn=burn,output=output_chain,stat='weights')
   1517             _modelFitMCMC_plotCorner(dp[int(burn*len(dp)):],columns=param_plot,output=output_corner)
   1518             param_best = {}

/Users/carolinaherrera/splat/splat/model.py in _modelFitMCMC_plotChains(dp, **kwargs)
   1613         for dp in inp: v.extend(list(dp[ms].values))
   1614         plt.subplot(int('{}1{}'.format(nplots,i+1)))
-> 1615         yr = [numpy.min(v),numpy.max(v)]
   1616         yr[0] -= 0.05*(yr[1]-yr[0])
   1617         yr[1] += 0.05*(yr[1]-yr[0])

/Users/carolinaherrera/anaconda/lib/python3.6/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims)
   2350 
   2351     return _methods._amin(a, axis=axis,
-> 2352                           out=out, **kwargs)
   2353 
   2354 

/Users/carolinaherrera/anaconda/lib/python3.6/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: setting an array element with a sequence.

**Comment by aburgasser** [comment]
I think I got this fixed....?
