### ISSUE TITLE
Evolutionary models error

### ISSUE THREAD

**Issue by ElizabethMorh** [aburgasser/splat#103]
INPUT:
spev.modelParameters(model='burrows',teff=1988.71, logg=5.29)

OUTPUT:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-179bba40cbed> in <module>()
----> 1 spev.modelParameters(model='burrows',teff=1988.71, logg=5.29)

/home/diego/Documents/Python/splat/splat/evolve.py in modelParameters(*model, **kwargs)
    537         for p in pkeys:
    538             inparams[p] = mkwargs[p][i]
--> 539         par = _modelParametersSingle(model,**inparams)
    540         for p in list(EVOLUTIONARY_MODEL_PARAMETERS.keys()):
    541             outparams[p].append(par[p])

/home/diego/Documents/Python/splat/splat/evolve.py in _modelParametersSingle(*args, **kwargs)
    352                     vals = [lmodel[P[0][0]][ai][i],lmodel[P[0][0]][ai+1][aj]]
    353                     f = interp1d(lmodel['age'][ai:ai+2],vals)
--> 354                     Ge.append(f(numpy.log10(params['age'])))
    355             try:
    356                 f = interp1d(Ge, Ma)

/home/diego/anaconda3/lib/python3.6/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

/home/diego/anaconda3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    608         y_new = self._call(self, x_new)
    609         if not self._extrapolate:
--> 610             below_bounds, above_bounds = self._check_bounds(x_new)
    611             if len(y_new) > 0:
    612                 # Note fill_value must be broadcast up to the proper size

/home/diego/anaconda3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    640                              "range.")
    641         if self.bounds_error and above_bounds.any():
--> 642             raise ValueError("A value in x_new is above the interpolation "
    643                              "range.")
    644 

ValueError: A value in x_new is above the interpolation range.

**Comment by aburgasser** [comment]
This is probably fixed due to a major remod of the non-mass, non-age case, but I'm not actually seeing these errors in python3.5, so please double check
