### ISSUE TITLE
Minor: Wrong docstring for for Spectrum.sp.rvShift

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#104]
Docstring:
:Purpose: Shifts the wavelength scale by a radial velocity factor. This routine changes the underlying Spectrum object.

:Example:
   >>> import splat
   >>> import astropy.units as u
   >>> sp = splat.Spectrum(file='somespectrum',wunit=u.Angstrom)
   >>> sp.wave.unit
    Unit("Angstrom")
   >>> sp.toMicron()
   >>> sp.wave.unit
    Unit("micron")

**Comment by aburgasser** [comment]
oops! fixed
