### ISSUE TITLE
classifyByStandard

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#107]
Is there a way to classify by all standards (including sds and esds?), I couldn't find this in the docs 
From the code it looks it either or ?
Thanks
<img width="918" alt="screen shot 2017-08-07 at 10 35 11 am" src="https://user-images.githubusercontent.com/7990189/29038351-34e48e38-7b5c-11e7-90c6-b37e503a3661.png">

**Comment by aburgasser** [comment]
Yes, you can now do this! it takes a while to read in all the standards at once, but after that initial read it is relatively fast. here's an example with a young BD:

`sp = splat.getSpectrum(young=True,lucky=True)[0]
splat.classifyByStandard(sp,all=True,plot=True)
`
<img width="519" alt="screen shot 2017-10-23 at 5 53 50 pm" src="https://user-images.githubusercontent.com/5667900/31901966-29e5cda2-b81b-11e7-89be-d30ba6f92467.png">
