### ISSUE TITLE
Problem with the spm.modelFitGrid

### ISSUE THREAD

**Issue by dorsa-pearl** [aburgasser/splat#108]
I seem to be having a problem with this function. I worked with Niana and Elizabeth by inputting the same as them, but I get a strange error.  It works on their computer, but not mine. I have tried looking it up, but no progress. It might be an issue with SPLAT:

In : sp=splat.getSpectrum(shortname='1123+0400')
     sp[0]
     spm.modelFitGrid(sp[0])

Out: 
      Retrieving 1 file

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-e59994121d77> in <module>()
      2 #print(sp)
      3 sp[0]
----> 4 spm.modelFitGrid(sp[0])

C:\Users\dm_do\Desktop\Python\splat\splat\model.py in modelFitGrid(spec, **kwargs)
   1385 
   1386 # read in available model grid points
-> 1387     gridparam = _loadModelParameters(model_set) # Range parameters can fall in
   1388 #    tvals = numpy.arange(mlimits['teff'][0],mlimits['teff'][1]+mlimits['teff'][-1],mlimits['teff'][-1])
   1389 #    gvals = numpy.arange(mlimits['logg'][0],mlimits['logg'][1]+mlimits['logg'][-1],mlimits['logg'][-1])

C:\Users\dm_do\Desktop\Python\splat\splat\model.py in _loadModelParameters(*args, **kwargs)
    994     for ms in SPECTRAL_MODEL_PARAMETERS_INORDER:
    995         if ms=='teff' or ms =='logg' or ms=='z':
--> 996             parameters[ms] = [float(x) for x in parameters[ms]]
    997         parameters[ms].sort()
    998         parameters[ms] = numpy.array(parameters[ms])

C:\Users\dm_do\Desktop\Python\splat\splat\model.py in <listcomp>(.0)
    994     for ms in SPECTRAL_MODEL_PARAMETERS_INORDER:
    995         if ms=='teff' or ms =='logg' or ms=='z':
--> 996             parameters[ms] = [float(x) for x in parameters[ms]]
    997         parameters[ms].sort()
    998         parameters[ms] = numpy.array(parameters[ms])

ValueError: could not convert string to float: 'do\\Desktop\\Python\\splat\\reference\\SpectralModels\\btsettl08\\btsettl08'

**Comment by aburgasser** [comment]
this turned out to be an error in how we extracted the parameters from the filename, and is now resolved
