### ISSUE TITLE
Plotting the residuals between two spectra is giving incorrect answers (as compared to previous versions of splat)

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#109]
For some reason the residual keyword is giving a strange output when plotting spectra. See below the two plots, the top one is a previous version of SPLAT (maybe ~3 months ago) and the bottom is the newest version of SPLAT.

[L6comparison1.pdf](https://github.com/aburgasser/splat/files/1220229/L6comparison1.pdf)
[L6comparison2.pdf](https://github.com/aburgasser/splat/files/1220230/TEST.pdf)

My best guess is that both flux arrays are different lengths, and the residual keyword is subtracting them straight across, so it's not considering what wavelength each flux value corresponds to.

**Comment by aburgasser** [comment]
hmm, this seems to have been (accidentally?) fixed; the following commands:

> import splat
> sp = splat.getSpectrum(shortname='1115+1937')[0]
> splat.classifyByStandard(sp,plot=True)

yield this plot:

<img width="529" alt="screen shot 2017-10-23 at 5 50 04 pm" src="https://user-images.githubusercontent.com/5667900/31901849-a9250106-b81a-11e7-82ee-f088febaeb27.png">
