### ISSUE TITLE
Fix for compareSpextra fit_ranges bug

### ISSUE THREAD

**Issue by aggle** [aburgasser/splat#110]
In compareSpectra, the indexing exception that occurs if fit_ranges is a 1-D array is fixed with the following code, inserted just after the comment "# THERE IS A MAJOR FLAW HERE" (line 4202)
`
if numpy.ndim(fit_ranges) == 1:
        fit_ranges = numpy.expand_dims(fit_ranges, 0)
`
Since the code in general expects fit_ranges to be a container with possibly multiple ranges, this makes a single range compatible with that format.

**Comment by aburgasser** [comment]
ack, that section seems to have been modified out of existence in more recent versions; if you see the problem come up again, please let me know

**Comment by aggle** [comment]
great to hear. are these versions not merged with master yet?
