### ISSUE TITLE
Fix for elementwise comparison exception

### ISSUE THREAD

**Issue by aggle** [aburgasser/splat#111]
https://github.com/aburgasser/splat/blob/eb48b33457645a2a56c4684f72514cf3f737f887/splat/core.py#L1337

I think this bug is new to python 3, but the fix works for both 2 and 3. Since rng can be array, != tests each of the elements to see if they are False. It's better to use `if rng is not False` in this case, since it tests to see if rng is a boolean object with value False (see e.g. https://stackoverflow.com/questions/2209755/python-operation-vs-is-not)

**Comment by aburgasser** [comment]
Thank you! I think there are probably several of these hiding in the code
