### ISSUE TITLE
can't run sp.plot() or sp[0].plot()

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#112]
--------------------------
In[4]: sd = splat.Spectrum(name='2MASS J11582077+0435014')

In[5]: sd
Out[5]: SPEX_PRISM spectrum of 2MASS J11582077+0435014

In[6]: sd.plot()
Traceback (most recent call last):

  File "<ipython-input-6-b1e37ac9fc36>", line 1, in <module>
    sd.plot()

  File "/Users/daniella/Python/splat/splat/core.py", line 1376, in plot
    kwargs['xrange'] = [numpy.nanmin(self.wave.value),numpy.nanmax(self.wave.value)]

AttributeError: 'list' object has no attribute 'value'
---------------------------
In[8]: sd = splat.Spectrum(name='2MASS J11582077+0435014')

In[9]: sd[0].plot()

Traceback (most recent call last):

  File "<ipython-input-9-a0a60fa7e9ea>", line 1, in <module>
    sd[0].plot()

TypeError: 'Spectrum' object does not support indexing

**Comment by aburgasser** [comment]
I'm surprised the first command even returned everything, but indeed you can call an instance of a Spectrum object with just a name, but it has no wave, flux, or noise elements, and therefore barfs when you try to plot it. I think you are trying to search for a spectrum, in which case you should use getSpectrum:

`sp = splat.getSpectrum(name='2MASS J11582077+0435014') # returns an array of spectrum objects
`
if you are reading in a file you have to specify the file name:

`sp = splat.Spectrum(file='spectrumof1158.fits',name='2MASS J11582077+0435014') # single spectrum object
`
