### ISSUE TITLE
queryXmatch NameError

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#113]
`
<img width="828" alt="screen shot 2017-11-14 at 4 21 21 pm" src="https://user-images.githubusercontent.com/7990189/32812067-e7d2dbe6-c957-11e7-9c91-e87ae6a00430.png">

NameError: name 'prepDB' is not defined

**Comment by caganze** [comment]
I understand the error, I forgot that I need a 'DESIGNATION' column. Please ignore this.

**Comment by aburgasser** [comment]
actually this is an error, as there is a missing function; now added (prepDB).
