### ISSUE TITLE
Bizarre file behavior

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#116]
I am trying to run splat.classifyByStandard on a for loop. These are the first few files:
0                 NaN
1                 NaN
2    12937_12667.fits
3                 NaN
4    12134_11869.fits
5                 NaN
6    12139_11768.fits
7                 NaN
8                 NaN
9    12708_12437.fits

My code breaks down at i = 9, because the 12708_12437.fits is corrupted. I see that this file appears both in the local folder where I am running my code *and* in  /Python/splat/reference/Spectra. The copy in my local folder (which should have never been there) only weighs 239 bytes, so I place it in my Trash and empty the Trash. The other copy is in /Python/splat/reference/Spectra/ and weighs 14kb. I import splat again, re-run the code and it stops at the same point. I find that copies of those 4 files listed above have appeared in my local folder (while still existing in /Python/splat/reference/Spectra/), and that 12708_12437.fits is corrupted again, weighing only 239 bytes. I can't seem to break from this loop.

sp = splat.Spectrum(12708)
Traceback (most recent call last):

  File "<ipython-input-37-46e3d4f92361>", line 1, in <module>
    sp = splat.Spectrum(12708)

  File "/Users/daniella/Python/splat/splat/core.py", line 253, in __init__
    rs = readSpectrum(self.filename,**mkwargs)

  File "/Users/daniella/Python/splat/splat/core.py", line 3766, in readSpectrum
    with fits.open(os.path.normpath(file),ignore_missing_end=True) as data:

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)

  File "/anaconda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1032, in _readfrom
    raise IOError('Empty or corrupt FITS file')

OSError: Empty or corrupt FITS file

**Comment by daniellabardalezgagliuffi** [comment]
This is a path issue. The files magically appear in my local folder because they're being downloaded after splat doesn't find them in /Python/splat/reference/Spectra/. This means, it must not be looking in the right place. Either I need to enter a folder path every time as a global variable or modify my bashrc.

These are the relevant lines in my bashrc:
export PYTHONPATH="/Users/daniella/Python/:/Users/daniella/Python/splat/:$PYTHONPATH"
export SPLAT_PATH="/Users/daniella/Python/splat/:$SPLAT_PATH"

These are lines 3707-3724 of core.py where splat realizes it hasn't found the file in my local folder, and decides to download a *corrupt* file from the internet:

    if not os.path.exists(os.path.normpath(file)):
        nfile = folder+os.path.basename(kwargs['filename'])
        if not os.path.exists(os.path.normpath(nfile)):
            if verbose==True: print('Cannot find '+kwargs['filename']+' locally, trying online\n\n')
            online = checkAccess()
            if online == False:
                raise ValueError('\nCannot find files {} or {} locally, and you do not have remote access'.format(file,nfile))
        else:
            file=nfile
            kwargs['filename'] = file

# second pass: download file if necessary
#    online = not local
    if online == True:
       if checkOnline(url+file) == '':
           file = folder+os.path.basename(file)
           if checkOnline(url+file) == '':
               raise ValueError('\nCannot find file '+kwargs['filename']+' on SPLAT website\n\n')

What needs to be modified in the bashrc?

Thanks!

**Comment by aburgasser** [comment]
Issue partially resolved - this was due to blank files with the same name being present in the directory Daniella was working in.

Simple workaround is to delete those files or move to a new directory; however, code should have a "try...except" to cover this.

Since we'll be going offline shortly, will probably be left as "deferred maintenance"
