### ISSUE TITLE
Missing filters on typeToMag

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#118]
or maybe different syntax?

spem.typeToMag(18,filt='2MASS J')
Out[315]: (11.127527039999999, 0.4)
spem.typeToMag(18,filt='2MASS H')
Out[316]: (nan, nan)
spem.typeToMag(18,filt='2MASS K')
Out[317]: (nan, nan)
spem.typeToMag(18,filt='2MASS KS')
Out[318]: (nan, nan)
spem.typeToMag(18,filt='WISE W1')
Out[319]: (nan, nan)
spem.typeToMag(18,filt='WISE W2')
Out[320]: (9.4752251200000011, 0.4)
spem.typeToMag(18,filt='SDSS r')
Out[321]: (nan, nan)
spem.typeToMag(18,filt='SDSS i')
Out[322]: (nan, nan)
spem.typeToMag(18,filt='SDSS z')
Out[323]: (nan, nan)

**Comment by aburgasser** [comment]
Not a bug - what filters are permitted depends on the relation you are using. By default this is the Filippazzo relation. if you set verbose = True:

spem.typeToMag(18,'2MASS J',verbose=True)

Using Absolute 2MASS_J/SpT relation from Filippazzo, J. C. et al. (2015, ApJ, 810, 158)
Out[12]:
(11.127527039999999, 0.4)

spem.typeToMag(18,'2MASS H',verbose=True)

Filter 2MASS_H is not among the filters defined for the filippazzo2015 absolutel magnitude relation; try: ['WISE_W2', '2MASS_J']
Out[15]:
(nan, nan)

to find out what relations are available type:

spem.typeToMag?
