### ISSUE TITLE
Install issues: package_data, SyntaxError

### ISSUE THREAD

**Issue by vidakris** [aburgasser/splat#120]
I had some troubles with installing splat. I tried pip install both in OSX and linux environments, and also with the github version. The pip install failed with:

Collecting splat
  Using cached SPLAT-0.32.tar.gz
    Complete output from command python setup.py egg_info:
    error in SPLAT setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z6/wcqvxxjj7sn3vc9jw9p5sdk80000gp/T/pip-build-2uXocJ/splat/

After that I downloaded the github version, which gave

  File "/Users/vidak/splat/splat/core.py", line 5325
    plotSpectrum(sp1,spcomp,sp1-spcomp,**kwargs,labels=[sp1.name,sp2.name,'{} = {}'.format(statistic,stat)])
                                               ^
SyntaxError: invalid syntax

and
In [6]: import splat
  File "/Users/vidak/splat/splat/core.py", line 5585
    def measureIndex(sp,*args,method='ratio',sample='integrate',nsamples=100,noiseFlag=True,**kwargs):
                                   ^
SyntaxError: invalid syntax

in python version 2.7. I fixed these by putting **kwargs to the end of the line, before ')' and *args before '**kwargs'. After that the import worked fine. Is this a general issue or just on my installation?

**Comment by aburgasser** [comment]
the pip install is currently not working; we haven't figured out how to package in the data downloads with this installation (and that version is also out of date).

Thank you for catching and solving the bugs on the github install - indeed, py2.7 seems to care about the order of *args & **kwargs while py3+ does not. I checked that the install worked with the update version.
