### ISSUE TITLE
Chabrier 2003 or 2005?

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#121]
Not really an issue. In splat.simulate, under simulateMasses, the description for the Chabrier IMF is that of 2003, but the code looks like a piece-wise lognormal, more like that of Chabrier 2005, so I wanted to make sure that the code corresponds to 2003. Apparently the difference is significant, especially around the lowest-mass objects, and Chabrier 2005 is preferred (according to Michael Meyer). Thanks!

**Comment by aburgasser** [comment]
both of these are now in the code; if you chose model='chabrier 2005' you'll get the 2005 one
