### ISSUE TITLE
Model Interpolation Problem

### ISSUE THREAD

**Issue by chihchunhsu** [aburgasser/splat#124]
In [14]: sp = spmd.getModel(instrument='NIRSPEC-O33-RAW',teff=1550,logg=5.)

Input value for teff = 1550 out of range for model set BTSettl2008

Input value for logg = 5.0 out of range for model set BTSettl2008

Input value for z = 0.0 out of range for model set BTSettl2008

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-a2e8717a0725> in <module>()
----> 1 sp = spmd.getModel(instrument='NIRSPEC-O33-RAW',teff=1550,logg=5.)

/Users/dinohsu/projects/splat/splat/model.py in getModel(*args, **kwargs)
   2022 
   2023     '''
-> 2024     return loadModel(*args, **kwargs)
   2025 
   2026 

/Users/dinohsu/projects/splat/splat/model.py in loadModel(modelset, instrument, raw, sed, *args, **kwargs)
   1971         if file=='':
   1972             if kwargs['force']: raise NameError('\nCould not find '+kwargs['filename']+' locally\n\n')
-> 1973             else: sp = _loadInterpolatedModel(**kwargs)
   1974         else: kwargs['filename'] = kwargs['filename']+'.gz'
   1975 #                kwargs['local']=False

/Users/dinohsu/projects/splat/splat/model.py in _loadInterpolatedModel(*args, **kwargs)
   2115 # first get model parameters
   2116     if _checkModelParametersInRange(mkwargs) == False:
-> 2117         raise ValueError('\n\nModel parameter values out of range for model set {}\n'.format(mkwargs['model']))
   2118 
   2119 # check that given parameters are in range - RETHINK THIS

ValueError: 

Model parameter values out of range for model set BTSettl2008

In [15]: sp = spmd.getModel(instrument='NIRSPEC-O33-RAW',teff=1550,logg=5.,model
    ...: set='btsettl08')

Input value for teff = 1550 out of range for model set BTSettl2008

Input value for logg = 5.0 out of range for model set BTSettl2008

Input value for z = 0.0 out of range for model set BTSettl2008

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-4125c81e8a71> in <module>()
----> 1 sp = spmd.getModel(instrument='NIRSPEC-O33-RAW',teff=1550,logg=5.,modelset='btsettl08')

/Users/dinohsu/projects/splat/splat/model.py in getModel(*args, **kwargs)
   2022 
   2023     '''
-> 2024     return loadModel(*args, **kwargs)
   2025 
   2026 

/Users/dinohsu/projects/splat/splat/model.py in loadModel(modelset, instrument, raw, sed, *args, **kwargs)
   1971         if file=='':
   1972             if kwargs['force']: raise NameError('\nCould not find '+kwargs['filename']+' locally\n\n')
-> 1973             else: sp = _loadInterpolatedModel(**kwargs)
   1974         else: kwargs['filename'] = kwargs['filename']+'.gz'
   1975 #                kwargs['local']=False

/Users/dinohsu/projects/splat/splat/model.py in _loadInterpolatedModel(*args, **kwargs)
   2115 # first get model parameters
   2116     if _checkModelParametersInRange(mkwargs) == False:
-> 2117         raise ValueError('\n\nModel parameter values out of range for model set {}\n'.format(mkwargs['model']))
   2118 
   2119 # check that given parameters are in range - RETHINK THIS

ValueError: 

Model parameter values out of range for model set BTSettl2008

**Comment by aburgasser** [comment]
this was a nasty bug due to python version differences (specifically from 3.5 to 3.6), but all fixed
