### ISSUE TITLE
measureIndexSet got multiple values for "method"

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#127]
Example straight from the documentation:

sp = splat.getSpectrum(shortname='1555+0954')[0]
print(splat.measureIndexSet(sp, set = 'reid'))

Retrieving 2 files

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-5c22404295ed> in <module>()
      1 sp = splat.getSpectrum(shortname='1555+0954')[0]
----> 2 print(splat.measureIndexSet(sp, set = 'reid'))

~/Python/splat/splat/core.py in measureIndexSet(sp, set, **kwargs)
   5943     result = {'set': set, 'bibcode': refcode}
   5944     for i,n in enumerate(names):
-> 5945         ind,err = measureIndex(sp,*ranges[i],method=methods[i],sample=samples[i],**kwargs)
   5946         result[n] = (ind,err)
   5947 

TypeError: measureIndex() got multiple values for argument 'method'

**Comment by daniellabardalezgagliuffi** [comment]
Essentially all index-based classifications have this same error.

splat.classifyGravity(sp)
splat.classifyByIndex(sp)

Please fix me! 😱

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-dc996884aa6b> in <module>()
----> 1 splat.classifyByIndex(sp)

~/Python/splat/splat/core.py in classifyByIndex(sp, *args, **kwargs)
   4259     elif (set.lower() == 'burgasser'):
   4260         if (rem_flag or len(args) == 0):
-> 4261             indices = measureIndexSet(sp, **kwargs)
   4262         sptoffset = 20.
   4263         coeffs = { \

~/Python/splat/splat/core.py in measureIndexSet(sp, set, **kwargs)
   5943     result = {'set': set, 'bibcode': refcode}
   5944     for i,n in enumerate(names):
-> 5945         ind,err = measureIndex(sp,*ranges[i],method=methods[i],sample=samples[i],**kwargs)
   5946         result[n] = (ind,err)
   5947 

TypeError: measureIndex() got multiple values for argument 'method'

**Comment by aburgasser** [comment]
fixed!
