### ISSUE TITLE
Return error for getStandard

### ISSUE THREAD

**Issue by MRickardUK** [aburgasser/splat#129]
Command 'sp3 = splat.getStandard('L1.0beta')' returns the error:

Type L1.0 is not in  standards: try one of the following:
['L0.0beta', 'L1.0beta', 'L2.0beta', 'L3.0beta', 'L6.0beta', 'M8.0beta']

Error being that the getStandard was fetching L1.0beta standard, the return says this was not available but then suggests trying the L1.0beta, the one that was requested.

**Comment by aburgasser** [comment]
Got it, fixed!
