### ISSUE TITLE
Invalid syntax Error for Splat

### ISSUE THREAD

**Issue by dorsa-pearl** [aburgasser/splat#131]
I received this error as I was running "Import splat.model":

My command: 
import splat.model as spm
Result: 
 File "/users/dm_do/desktop/python/splat/splat/model.py", line 2864
    model = loadModel(**p,force=True)
                         ^
SyntaxError: invalid syntax

**Comment by aburgasser** [comment]
hmm, that I can't reproduce on either python 2.7.12 or python 3.5.3. If you go to your terminal and just type python, which comes after? for example, when I do that I get:

bash-3.2$ python
Python 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by aburgasser** [comment]
actually, I found the issue. Go ahead and update your splat code by using your terminal, cd into the folder that contains splat, and type "git pull"

**Comment by dorsa-pearl** [comment]
Thank You!
