### ISSUE TITLE
typeToMag only works on J band for Filippazzo (default)

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#134]
print(empirical.typeToMag('L3', '2MASS H'))
(nan, nan)

print(empirical.typeToMag('L3', '2MASS KS'))
(nan, nan)

print(empirical.typeToMag('L3', '2MASS J'))
(12.873716539999998, 0.4)

**Comment by aburgasser** [comment]
That's because Filippazzo did not define abs mag relations except for J-band!
