### ISSUE TITLE
classifybyStandard verbose states using subdwarfs even when not

### ISSUE THREAD

**Issue by MRickardUK** [aburgasser/splat#138]
splat.classifyByStandard(sp1, verbose=True, sd=False)

where sp1 is my observed spectra. Verbose then states:
Using subdwarf standards

But the closest match standard returned is not from a subdwarf.

Not a major issue but through me off for a while as I suddenly thought there were subdwarf characteristics that I had missed in the rest of my analysis.

**Comment by aburgasser** [comment]
hmm, can you copy in your full command list? when I try this I get the following:

> sp = splat.getSpectrum(spt='M9',subdwarf=True,lucky=True)
> splat.classifyByStandard(sp[0],plot=True,sd=True,verbose=True)
> 
> Using subdwarf standards
> Type sdM2.0: statistic = 3637960.8183932933, scale = 3.385008778183482e-15
> Type sdM4.0: statistic = 2684104.654434258, scale = 3.240243262058065e-15
> Type sdM5.0: statistic = 2951471.07047887, scale = 3.435724577384231e-15
> Type sdM5.5: statistic = 1779955.9772499315, scale = 3.4413517454203223e-15
> Type sdM6.0: statistic = 2032305.4223966645, scale = 3.397887609416448e-15
> Type sdM7.0: statistic = 1016039.6947979438, scale = 3.339808418316062e-15
> Type sdM8.0: statistic = 1476966.9039403999, scale = 3.574070648562339e-15
> Type sdM9.5: statistic = 1952814.9449190428, scale = 3.7128576834318295e-15
> Type sdL0.0: statistic = 322779.08226356993, scale = 0.4684970295174889
> Type sdL3.5: statistic = 2889710.1986012133, scale = 4.1645573532705e-15
> Type sdL4.0: statistic = 3276047.9895164226, scale = 8.42758083104525
> 
> Best match to sdL0.0 standard
> Best spectral type = sdL0.0+/-0.5

whereas if I don't set subdwarf=True:

> splat.classifyByStandard(sp[0],plot=True,verbose=True)
> 
> Using subdwarf standards
> Type M0.0: statistic = 5266241.361943455, scale = 3.3598300355243456e-15
> Type M1.0: statistic = 4471402.747918308, scale = 3.378824397014865e-15
> Type M2.0: statistic = 3571031.645501312, scale = 3.3968977478191227e-15
> Type M3.0: statistic = 3169626.960626547, scale = 3.4240412607208198e-15
> Type M4.0: statistic = 1867735.4437821538, scale = 3.0900587384951916e-15
> Type M5.0: statistic = 1196733.2512517702, scale = 3.085050063083775e-15
> Type M6.0: statistic = 996799.3889603419, scale = 3.049516449842044e-15
> Type M7.0: statistic = 676966.9725547684, scale = 8.81894805296289
> Type M8.0: statistic = 1865510.2103509982, scale = 2.797372838701092e-15
> Type M9.0: statistic = 3676214.042527305, scale = 2.543793730805055e-15
> Type L0.0: statistic = 3825127.9176042574, scale = 2.5361191652669517e-15
> Type L1.0: statistic = 4514991.715842241, scale = 2.551751421806605e-15
> Type L2.0: statistic = 7842074.786429006, scale = 2.18016543957937e-15
> Type L3.0: statistic = 7831972.421384376, scale = 2.286798746923473e-15
> Type L4.0: statistic = 7894957.265405672, scale = 2.2530422769799797e-15
> Type L5.0: statistic = 9215436.839121314, scale = 2.050648893282629e-15
> Type L6.0: statistic = 9553544.355015513, scale = 1.9292406616475487e-15
> Type L7.0: statistic = 12303192.200637344, scale = 1.621590666831195e-15
> Type L8.0: statistic = 10746340.757266242, scale = 1.7628786431992246e-15
> Type L9.0: statistic = 8555652.920655653, scale = 2.0533672058954492e-15
> Type T0.0: statistic = 5175616.536918532, scale = 2.6270449486737726e-15
> Type T1.0: statistic = 4155854.0541452887, scale = 2.962182906731632e-15
> Type T2.0: statistic = 4801457.262909821, scale = 3.249256304740817e-15
> Type T3.0: statistic = 4314806.820020715, scale = 3.9828926857386915e-15
> Type T4.0: statistic = 6708414.249283274, scale = 4.3554873684557714e-15
> Type T5.0: statistic = 11590058.22596549, scale = 4.776249892003668e-15
> Type T6.0: statistic = 13721387.89223746, scale = 4.955182612871638e-15
> Type T7.0: statistic = 15727122.26830364, scale = 4.9535791820572014e-15
> Type T8.0: statistic = 17237847.635007918, scale = 5.042383668151046e-15
> Type T9.0: statistic = 18412571.36937388, scale = 5.405426981618977e-15
> 
> Best match to M7.0 standard
> Best spectral type = M7.0+/-0.5

clearly it's claiming the wrong standards (minor fix) but using the right ones.

**Comment by aburgasser** [comment]
and I've now fixed the reporting issue, so perhaps this is resolved?
