### ISSUE TITLE
classifyByStandard can't find standard

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#14]
In: spc = splat.getSpectrum(designation='J1632561+3505073')[0]

Out: Retrieving 1 file

In: print(splat.classifyByStandard(spc))

Out: 
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
No spectra in the SPL database match the selection criteria
('L1.0', 0.5)

**Comment by aburgasser** [comment]
hmm, I'm not getting this error. I wonder if some of the standards are "unpublished" and therefore unreachable if you're offline. let me check

**Comment by aburgasser** [comment]
yup, that was it.  OK, will add a job to move all standards to the public folder

**Comment by aburgasser** [comment]
this is now fixed
