### ISSUE TITLE
splat filtermag

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#145]
There might be a sign error in the way splat computes magnitudes
`splat.initializeStandards()`
`sp=splat.STDS_DWARF_SPEX['T9.0']`
`sp.filterMag('NICMOS F140W')`

The output is (-12.211770678575347, 0.043722210970631205); shouldn't this be +12?

Thanks

**Comment by aburgasser** [comment]
The spectra contained in the library are not flux calibrated, so if you try to measure a magnitude straight off of one, it will likely give you a skewed value. In this case, I suspect the spectrum is normalized, and hence enormously "bright". You either need to scale the spectrum to its apparent/absolute magnitude, or just measure colors (which don't depend on the flux scaling). Most of the standards have 2MASS magnitudes built in, so you can do this automatically by:

sp = splat.STDS_DWARF_SPEX['T9.0']
sp.fluxCalibrate('2MASS J',float(sp.j_2mass))
sp.filterMag('NICMOS F140W')

output: (16.88166336068887, 0.039290090747856506)
