### ISSUE TITLE
Reading models as spectrum objects

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#148]
I’m trying to read some of Caroline Morley’s models as spectrum objects like this:

sp = splat.Spectrum(filename='/Users/daniella/Research/Relations/Morley2012/Morley6/sp_t1300g3000f5_010_b’)

But I get an error that the instrument is unknown, which is fair because they come from no instrument. Is there a workaround for this?

Thanks!

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-33-4ee650927403> in <module>()
----> 1 sp = splat.Spectrum(filename='/Users/daniella/Research/Relations/Morley2012/Morley6/sp_t1300g3000f5_010_b',instrument='UNKNOWN')

~/Python/splat/splat/core.py in __init__(self, *args, **kwargs)
    560             inst = 'UNKNOWN'
    561         self.instrument = inst
--> 562         for k in list(INSTRUMENTS[self.instrument].keys()): setattr(self,k,INSTRUMENTS[self.instrument][k])
    563         self.slitpixelwidth = (self.slitwidth/self.pixelscale).value
    564         if kwargs.get('resolution',False) != False:

KeyError: 'UNKNOWN'

**Comment by daniellabardalezgagliuffi** [comment]
I updated splat and this works!

spec = splat.Spectrum(wave=sp[0]['microns'].values,flux=sp[0]['Flux'].values,ismodel=True,funit=u.erg/(u.cm**2*u.s*u.Hz),funit_label='erg cm\^-2 s^-1 Hz\^-1')

**Comment by aburgasser** [comment]
yup, we created an "UNKNOWN" instrument ;)
