### ISSUE TITLE
Setting up SPLAT on Windows

### ISSUE THREAD

**Issue by SharonDiamant** [aburgasser/splat#150]
Hi everyone, I have an issue with setting up SPLAT on my Windows 10 computer.  After I installed the SPLAT code via GitHub.com, I tried to run it and I get some errors: 

![splat-printscreen](https://user-images.githubusercontent.com/63069438/78284469-c5baa180-751f-11ea-9dc1-1f25b21f5c9b.png)

![splat-printscreen2](https://user-images.githubusercontent.com/63069438/78284512-d23efa00-751f-11ea-9875-097f56aa5b37.png)

The first printscreen shows the error after I run it for the first time. I tried to run the getSpectrum() function. I tried to import every package and then I dismissed each package to see if it would help but nothing solved the error. 
Strangely enough, after I run it for the second time (and after that) I get a second error shown in the second printscreen. It seems that there may be an issue with the citations package or I am doing something wrong. 
Does anyone have an idea what is going on? Thank you in advance!

**Comment by aburgasser** [comment]
try to reupdate; i've eliminated that function that was causing the problem and it may work now
