### ISSUE TITLE
splat.measureIndexSet(sp, set='bardalez') doesnt return measurements for H2O-Y and J-curve

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#157]
I'm using splat version 2020.04.19 and I see H2O-Y and J-curve both in initialize.py so I cannot figure out why the index set is being called without these two indices.

**Comment by daniellabardalezgagliuffi** [comment]
This is my bad again, I interpolated the spectra to a common wavelength range that started around 1.1 so I couldn't measure 1.04-1.07 which are needed for both of those indices. Sorry!

**Comment by aburgasser** [comment]
Actually, H2O-Y wasn't present, nor was CH4-J! I've gone ahead and added this in and confirmed that the indices all come out.
