### ISSUE TITLE
splat.classifyByTemplate fails due to lack of Spectrum.dof attribute

### ISSUE THREAD

**Issue by brackham** [aburgasser/splat#161]
`splat.classifyByTemplate()` raises `AttributeError: 'Spectrum' object has no attribute 'dof'`

Here's a minimal example reproducing the problem:

![image](https://user-images.githubusercontent.com/16804223/132756127-c8bf947b-2b7e-4a4a-9a52-791b7d63f170.png)

In `splat/splat/core.py` it looks like `self.dof` was commented out on line 511 at some point when instrument-specific information was removed from that class.

https://github.com/aburgasser/splat/blob/5ee0da82f19017e900ee83af94609dbe9f8a0ea4/splat/core.py#L511

Simply removing `dof=sp.dof` from line 6389 of `splat/splat/core.py` fixed the problem for me because `utilities.weightedMeanVar()` calculates a `dof` if none is provided.

Offending line:

https://github.com/aburgasser/splat/blob/5ee0da82f19017e900ee83af94609dbe9f8a0ea4/splat/core.py#L6389

Suggested fix:

`mean,var = weightedMeanVar(sspt,stat,method='ftest')`

**Comment by aburgasser** [comment]
fixed!
