### ISSUE TITLE
Github Install Documentation Incorrect

### ISSUE THREAD

**Issue by JosephKarpinski** [aburgasser/splat#174]
The third step of the installation documentation is:
python setup.py

This generates an error.
It should be:
python setup.py install

See attached.
<img width="824" alt="Screenshot 2023-08-06 at 8 42 36 AM" src="https://github.com/aburgasser/splat/assets/37123616/139e37c5-065b-493d-ae4e-f59837eba3be">

<img width="824" alt="Screenshot 2023-08-06 at 8 42 57 AM" src="https://github.com/aburgasser/splat/assets/37123616/f9f10e73-af3a-4a0f-815f-5c560b8270a3">

**Comment by aburgasser** [comment]
thanks! corrected
