### ISSUE TITLE
Missing SPEX-PRISM fits files

### ISSUE THREAD

**Issue by JosephKarpinski** [aburgasser/splat#175]
Hi,

Where can I find these missing SPEX-PRISM fits files?

See attached below:

Thanks!

<img width="1159" alt="Screenshot 2023-08-10 at 9 51 11 AM" src="https://github.com/aburgasser/splat/assets/37123616/ac01badf-b0f8-45ea-9cd9-8c150946818f">
<img width="1159" alt="Screenshot 2023-08-10 at 9 52 41 AM" src="https://github.com/aburgasser/splat/assets/37123616/b961082a-028f-47ef-a756-6be232e50f92">
<img width="1159" alt="Screenshot 2023-08-10 at 9 53 24 AM" src="https://github.com/aburgasser/splat/assets/37123616/fd689d98-94cd-442c-a24c-efff281789a7">
<img width="1159" alt="Screenshot 2023-08-10 at 9 54 26 AM" src="https://github.com/aburgasser/splat/assets/37123616/067f40cf-9c95-4665-9876-a84123318dff">
<img width="1159" alt="Screenshot 2023-08-10 at 9 54 50 AM" src="https://github.com/aburgasser/splat/assets/37123616/24c93797-ed7c-4535-bf10-a3873dde4893">

**Comment by Tianxing-Sky-Zhou** [comment]
Same error occurs to me after a recent update. A significant amount of SPEX-PRISM fits files went missing. This was not an issue when I was using July 5th's version

**Comment by aburgasser** [comment]
Issues noted; we're in a bit of a busy time right now but I'll track this down as soon as possible.

**Comment by aburgasser** [comment]
there were several unpublished spectra missing from the original library; these have now been added
