### ISSUE TITLE
Easy Fix - ImportError: cannot import name 'trapz' from 'scipy.integrate' (/opt/miniconda3/lib/python3.12/site-packages/scipy/integrate/__init__.py)

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#180]
We just need to update the code from "trapz" to "trapezoid"

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapezoid.html#scipy.integrate.trapezoid

They have removed "trapz" as a function. Usage between the two is the same.

**Comment by carlosiac** [comment]
I had to update it in these 3 files in splat/splat/:
core.py 
utilities.py
photometry.py

**Comment by aburgasser** [comment]
done!
