### ISSUE TITLE
classifyByStandard

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#24]
splat.classifyByStandard claims that the spectrum has no noise column, when in reality it does.

specfolder = '/Users/daniella/idl/spexbinaryfit/all/'
spc = splat.readSpectrum(specfolder+'spex_prism_0333+0014_081214.txt')
splat.classifyByStandard(spc,plot=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-220-5a0ceb6013ad> in <module>()
      1 specfolder = '/Users/daniella/idl/spexbinaryfit/all/'
      2 spc = splat.readSpectrum(specfolder+'spex_prism_0333+0014_081214.txt')
----> 3 splat.classifyByStandard(spc,plot=True)

/Users/daniella/Python/splat/splat.py in classifyByStandard(sp, *args, **kwargs)
   1216 
   1217 # which comparison statistic to use
-> 1218     if numpy.isnan(numpy.median(sp.noise)):
   1219         compstat = 'stddev_norm'
   1220     else:

AttributeError: 'dict' object has no attribute 'noise'

**Comment by aburgasser** [comment]
readSpectrum does not return a Spectrum object; it is an internal function that shouldn't be used (I'll make sure this is more clear in the documentation). Instead, run:

specfolder = '/Users/daniella/idl/spexbinaryfit/all/'
spc = splat.Spectrum(specfolder+'spex_prism_0333+0014_081214.txt')
splat.classifyByStandard(spc,plot=True)

Note that you will currently get an error message say "No spectra in the SPL database match the selection criteria", but you can ignore this (the updated SPLAT as of Feb 26 will not have this error)
