### ISSUE TITLE
File cannot be loaded 

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#25]
filename= '11731_11594.fits'

**Comment by aburgasser** [comment]
this is an supernova spectrum, and what was happening is that the code was returning only VLM objects by default. I've now eliminated that constraint, but be aware that you may get lots of non-VLM things as a result. The prevent this, be sure to set vlm=True in getSpectrum or searchLibrary.

**Comment by caganze** [comment]
I downloaded the new splat version and set the option vlm= True but I still
get the files '11295_10026.fits','11190_11405.fits' . I am going to exclude
them in the database search for now.

Thank you

Christian Aganze
Department of Physics
Morehouse College class of 2016
Phone: +1 404-692-8065
