### ISSUE TITLE
Unicode Decode Error when trying to use splat.Spectrum to read in/load a spectrum fits file

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#29]
specfolder = '/Users/daniella/idl/spexbinaryfit/all/'
spc = splat.Spectrum(specfolder+'spex_prism_0001-0942W_121027.fits')
splat.classifyByStandard(spc,plot=True)

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-387-51f7d52a73ff> in <module>()
      1 specfolder = '/Users/daniella/idl/spexbinaryfit/all/'
----> 2 spc = splat.Spectrum(specfolder+'spex_prism_0001-0942W_121027.fits')
      3 splat.classifyByStandard(spc,plot=True)

/Users/daniella/Python/splat/splat.py in __init__(self, *args, **kwargs)
    372             sdb = keySpectrum(self.idkey)
    373             if sdb != False:
--> 374                 self.filename = sdb['DATA_FILE'][0]
    375         elif self.model == False and self.filename != '':
    376             kwargs['filename']=self.filename

/Users/daniella/Python/splat/splat.py in searchLibrary(*args, **kwargs)
   3287             L7.0IIp:
   3288         >>> print splat.typeToNum(50)
-> 3289             Spectral type number must be between 0 (K0) and 49.0 (Y9)
   3290             nan
   3291     '''

/Users/daniella/miniconda3/lib/python3.5/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    285             try:
    286                 with get_readable_fileobj(table) as fileobj:
--> 287                     table = fileobj.read()
    288             except ValueError:  # unreadable or invalid binary file
    289                 raise

/Users/daniella/miniconda3/lib/python3.5/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 57291: invalid continuation byte

**Comment by aburgasser** [comment]
hmm, this looks like a messy one; can you email me the spectrum file so I can try this on my end?

**Comment by daniellabardalezgagliuffi** [comment]
Hey Adam,

Thanks for looking into this. I actually don’t have that one in my computer, but I just tried running the same piece of code with this one and gave me the same error:




I was going to ask you tomorrow where I could update my SpeX library.

Thanks!

Daniella

**Comment by aburgasser** [comment]
you'll have to email me the spectrum directly, i don't see a file in this thead

**Comment by aburgasser** [comment]
Could not reproduce this in python 2.7

**Comment by aburgasser** [comment]
I've modified the code to throw a warning for this, instead of crashing, but this is potentially fatal for code. Will need to analyze this with computer running Python 3.X to solve, possibly need to tweak the database.

**Comment by aburgasser** [comment]
problem isolated to source database, and I think I found the offending byte.  Please do an update and try again.

**Comment by aburgasser** [comment]
error has been found - one bad character in source file - solved
