### ISSUE TITLE
Interpolated models interpolate over parameter space that doesn't exist

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#35]
Interpolations currently happen over all the possible values for Teff, logg, and z for given models. However, if you are looking at, say, low-Teff range where z = 0 and no other value, this should do something rather than try and fit other values of z that exist for higher-Teff models.

**Comment by ctheissen** [comment]
It might be easier to use a KDTree and look up the nearest neighbor value based on the parameter space of the available models. I'm not sure what the benefit is of using linear interpolation since, in principle, it is just going to go to the nearest neighbor anyways. This also might speed things up quite a bit.

**Comment by aburgasser** [comment]
just fixed this in latest version - it now looks in the 8 "quadrants" of model space around a given (T,g,z) set and grabs the nearest model.
