### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#37]
I downloaded the new version of splat but when I try to import splat, the following error is displayed:

**File "splat\__init__.py", line 1, in <module>
    from splat import *

  File "splat\splat.py", line 94, in <module>
    DB_SOURCES = fetchDatabase(DB_SOURCES_FILE)

  File "splat\splat_db.py", line 343, in fetchDatabase
    raise NameError('\nCould not find '+kwargs['folder']+' locally or on SPLAT website\n\n')

NameError: 
Could not find /db/ locally or on SPLAT website**

It seems like /db/ folder can't be located even if it's clearly downloaded

**Comment by aburgasser** [comment]
this was an ordering issue of commands - now fixed

**Comment by caganze** [comment]
After re-downloading splat yesterday, the issue has returned.

Christian Aganze
Department of Physics
Morehouse College class of 2016
Phone: +1 404-692-8065
