### ISSUE TITLE
Standards do not load offline

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#40]
11335_10505.fits
11364_10806.fits
11181_10187.fits
10823_11422.fits
12004_10444.fits
10829_10104.fits
11182_10188.fits
10822_11283.fits
10824_11423.fits
10821_11058.fits
10107_10315.fits
11072_11527.fits
10600_10957.fits
10592_11111.fits
10675_11572.fits
10351_10583.fits
10375_10696.fits
10678_10105.fits
10115_11254.fits
10771_10871.fits
10767_10591.fits
10017_10945.fits
10034_10874.fits
10021_11106.fits
10200_11236.fits
10159_10513.fits
10126_10349.fits
11536_10509.fits

**Comment by caganze** [comment]
Script 

import splat
STDs= [splat.SPEX_STDFILES[key] for key in STD_NAMES]
for f in STDs:
    try:
        splat.Spectrum(f)
    except NameError:
        print f

**Comment by aburgasser** [comment]
this appears to be a problem in the way your SPLAT pathway is set on your windows machine. It doesn't appear that your environmental variables are being read in, and your path (which you sent separately) is corrupted.  The immediate fix is to always start python/ipython from the splat code directly, or upon opening ipython enter the commands:

import splat
splat.SPLAT_PATH = '[pathway to the splat code folder]'

But it would be good to figure out the environmental things!
