### ISSUE TITLE
splat has no attributes?

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#50]
>>> import splat
>>> splat.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'splat' has no attribute 'test'

**Comment by ctheissen** [comment]
Did you do "splat.test()" or "splat.test"? It should be the former.

**Comment by ctheissen** [comment]
I just pulled the newest version. I can run test(), but it fails due to key errors.

Example 1:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "splat.py", line 3246, in test
    grav = classifyGravity(sp)
  File "splat.py", line 1740, in classifyGravity
    sptn, spt_e = classifyByIndex(sp,string=False,set='allers')
  File "splat.py", line 1223, in classifyByIndex
    vals = numpy.polyval(coeffs[index]['coeff'],numpy.random.normal(indices[index][0],indices[index][1],nsamples))*sptfact
KeyError: 'K2

Example 2:
  File "<stdin>", line 1, in <module>
  File "/Users/ctheissen/repos/splat/splat.py", line 3246, in test
    grav = classifyGravity(sp)
  File "/Users/ctheissen/repos/splat/splat.py", line 1740, in classifyGravity
    sptn, spt_e = classifyByIndex(sp,string=False,set='allers')
  File "/Users/ctheissen/repos/splat/splat.py", line 1223, in classifyByIndex
    vals = numpy.polyval(coeffs[index]['coeff'],numpy.random.normal(indices[index][0],indices[index][1],nsamples))*sptfact
KeyError: 'H2O-H'

**Comment by daniellabardalezgagliuffi** [comment]
If I try to run splat.py from the command line I get a different error:

daniella$ python splat.py
Traceback (most recent call last):
  File "splat.py", line 86, in <module>
    from splat_db import *
  File "/Users/daniella/Python/splat/splat_db.py", line 14, in <module>
    import splat
  File "/Users/daniella/Python/splat/splat.py", line 96, in <module>
    DB_SOURCES = fetchDatabase(DB_SOURCES_FILE)
NameError: name 'fetchDatabase' is not defined

**Comment by aburgasser** [comment]
for the first and last error, make sure you've run your "bash" startup to set all of the system variables - this looks like an error of python not knowing where to look (try on UNIX command line "printenv").

The second (Chris) error is fixed - make sure to update.

**Comment by aburgasser** [comment]
actually for the command "python splat.py" - the "test" function here doesn't work this way - better to open ipython, "import splat" then "splat.test()".  I'll need to fix this.

**Comment by daniellabardalezgagliuffi** [comment]
OK, I can import splat from any directories, but can only run splat.test() successfully if I'm in the splat directory.

My bashrc has the following paths:
export PYTHONPATH="/Users/daniella/Python/splat/:$PYTHONPATH"
export PYTHONPATH="/Users/daniella/Python/:$PYTHONPATH"
export PATH="/Users/daniella/miniconda3/bin/:$PATH"

**Comment by daniellabardalezgagliuffi** [comment]
Fixed! It was a path issue: both /Users/daniella/Python and /Users/daniella/Python/splat were in the PYTHONPATH, so I assume python couldn’t find splat.py in the Python folder because it was in Python/splat.

Good thing to keep in mind. Thanks for the help!

Daniella
