### ISSUE TITLE
pono.ucsd.edu is down

### ISSUE THREAD

**Issue by aburgasser** [aburgasser/splat#51]
computer seems to have gone dark - communication issue at UCSD, or my machine?

**Comment by daniellabardalezgagliuffi** [comment]
Try again later. I’ve been having some internet issues this week where it would connect and disconnect, but only a couple of times.

**Comment by aburgasser** [comment]
and we're back.  Will need to solve this critical failure mode.

**Comment by aburgasser** [comment]
OK, now fixed, but things will be moved to a server
