### ISSUE TITLE
classifyByTemplate

### ISSUE THREAD

**Issue by ElizabethMorh** [aburgasser/splat#58]
Code line:
splat.classifyByTemplate(spc1,string=True,spt=['M5','M9'],force=True,snr=50,nbest=5,plot=True)

Error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-45-1537d67fdfd2> in <module>()
----> 1 splat.classifyByTemplate(spc1,string=True,spt=['M5','M9'],force=True,snr=50,nbest=5,plot=True)
      2 #splat.classifyByTemplate(spc1,force=True,snr=300,nbest=5,plot=True, select=('Mdwarfs'))

/Users/macbookpro/Documents/splat-master/splat.pyc in classifyByTemplate(sp, *args, **kwargs)
   2217         kwargs['legend'] = [sp.name,s.name]
   2218         kwargs['colors'] = ['k','r','b']
-> 2219         plotSpectrum(sp,s,sp-s,**kwargs)
   2220 
   2221 # string or not?

/Users/macbookpro/Documents/splat-master/splat_plot.pyc in plotSpectrum(*args, **kwargs)
    508         xrange = kwargs.get('xrange',[0.85,2.42])
    509         bound = xrange
--> 510         ymax = [s.fluxMax().value for s in sp]
    511         yrng = kwargs.get('yrange',map(lambda x: x*numpy.nanmax(ymax)+numpy.nanmax(zeropoint),[-0.02,1.2]))
    512         bound.extend(yrng)

/Users/macbookpro/Documents/splat-master/splat.pyc in fluxMax(self, **kwargs)
    937 
    938         return numpy.nanmax(self.flux.value[numpy.where(\
--> 939                 numpy.logical_and(self.wave > nanmin(self.wave)+0.1*(nanmax(self.wave)-nanmin(self.wave)),self.wave < nanmax(self.wave)-0.1*(nanmax(self.wave)-nanmin(self.wave))))])*self.funit
    940 
    941 

NameError: global name 'nanmin' is not defined

**Comment by aburgasser** [comment]
fixed - amazed this wasn't caught before!
