### ISSUE TITLE
SPLAT needed fixes for filterInfo and filterProperties

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#69]
Changes to splat.filterInfo:

Says:
WFC3 F167N: WFC3 F160W
Should say:
WFC3 F167N: WFC3 F167N

Says:
NIRC2 LP: WIRC Fe II
Should say:
NIRC2 LP: NIRC2 L'-band

Says:
NIRC2 M: WIRC Fe II
Should say:
NIRC2 M: NIRC2 M-band

Changes to splat.filterProperties:

1. Change description:

Filter: WIRCAM CH4 OFF
Current description: CFHT WIRCAM CH4-on

Filter: WIRCAM CH4 ON
Current description: CFHT WIRCAM CH4-off

Filter: NIRC2 FE2
Current description: WIRC Fe II

2. File not found:

Filter: WFC3 F164N
splat looks for wfc_F164M.txt
True HST WFC3 filter is F164 Narrow.

3. Add zero points (although I couldn't find them online):

Filters: 
WIRC BRGAMMA: WIRC H I Brackett Gamma
WIRC CH4L: WIRC CH4L
WIRC CH4S: WIRC CH4S
WIRC CO: WIRC CO
WIRC FE2: WIRC Fe II
WIRC H: WIRC H-cont
WIRC J: WIRC J-cont
WIRC K: WIRC K-cont
WIRC PABETA: WIRC H I Paschen Beta

4. Non-corresponding filter files:

Filter: WFC3 F167N
splat looks for wfc3_F160W.txt

5. Filter not available:

Filter: WFC3 F160W
Prints: WFC3 F160W not among the available filters: + list of filters from splat.filterInfo()

6. “ValueError: Not enough values to unpack (expected 2, got 0)”

All NIRC2 Filters:
NIRC2 J
NIRC2 H
NIRC2 K
NIRC2 KS
NIRC2 KP
NIRC2 KCONT
NIRC2 LP
NIRC2 M

7. “ValueError: too many values to unpack (expected 2)”

All IRAC Filters:
IRAC CH1
IRAC CH2
IRAC CH3
IRAC CH4

**Comment by aburgasser** [comment]
I think these are all covered
