### ISSUE TITLE
Object `splat.modelParameters` not found.

### ISSUE THREAD

**Issue by ElizabethMorh** [aburgasser/splat#71]
Line:  splat.modelParameters(temperature=2821.301,age=5)

Error: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-431ffd2ffca8> in <module>()
----> 1 splat.modelParameters(temperature=2821.301, age=5)

AttributeError: 'module' object has no attribute 'modelParameters'

**Comment by aburgasser** [comment]
There was a recent change in the code structure that hasn't been included in the documentation yet. You have to call in the "side packages" separately now:

In [1]: import splat.evolve as spel

In [2]: spel.modelParameters(teff=1200,logg=5.0)
You are using baraffe's models.
Out[2]: 
{'age': <Quantity 0.8004103895925054 Gyr>,
 'gravity': <Dex 5.0 dex(cm / s2)>,
 'luminosity': <Dex -4.765040252420802 dex(solLum)>,
 'mass': <Quantity 0.03405847587979601 solMass>,
 'radius': <Quantity 0.09651909962870645 solRad>,
 'temperature': <Quantity 1200.0 K>}

Note that there was an error in the evolve package that has now been fixed.
