### ISSUE TITLE
I am having issues reading in the spectrum for L8.0

### ISSUE THREAD

**Issue by pearsonkyle** [aburgasser/splat#72]
Hello, I am trying to read in a bunch of L8 spectra however when I type the code below I get an error

```python
import splat
specs = splat.getSpectrum(spt="L8.0")
```

A ValueError is raised and says this for me
```
C:\Users\Kyle\Programs\browndwarf\splat\splat\core.py in __init__(self, *args, **kwargs)
    241
    242 # populate information on source and spectrum from database
--> 243         if sdb != False:
    244             for k in sdb.keys():
    245                 setattr(self,k.lower(),str(sdb[k][0]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I think the issue lies with a duplicate entry for 10056 in source_data.txt. I can't seem to delete the duplicate entry for 10056 and have it read the table in properly

**Comment by aburgasser** [comment]
hmm, that looks like a funny way in which we try to assess whether a database table is present or not, and it does seem to be unique to L8 - I'll check the duplication entry and upload a correction shortly

**Comment by aburgasser** [comment]
Yup, that was it, a redundant source in db_source.  Thanks for catching that! I've uploaded updates source and spectral databases with about 300 more spectra

**Comment by pearsonkyle** [comment]
Thank you very much, I look forward to the update!
