### ISSUE TITLE
binary, spbinary, giant, subdwarf tags not working on getSpectrum

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#75]
getSpectrum works fine without any tags. When tags (binary, spbinary, giant, subdwarf == True) are introduced, getSpectrum can't find any suitable files to retrieve.

In[449]: print(sptn1[0])
optf = lambda x: splat.getSpectrum(optspt=x,lucky=True)
optf(sptn1[0])

20.5

Retrieving 1 lucky file
Out[449]:
[SPEX_PRISM spectrum of WISE J104915.57-531906.1A]

In[451]: print(sptn1[0])
optf = lambda x: splat.getSpectrum(optspt=x,lucky=True, binary=False, spbinary=False, giant=False, subdwarf=False)
optf(sptn1[0])

20.5

No files match search criteria

Out[451]:
[]

**Comment by aburgasser** [comment]
got it; all fixed
