### ISSUE TITLE
Is lucky=True on getSpectrum overriding optspt=x?

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#76]
When asked for a specific spectral type *and* lucky=True, the retrieved spectrum doesn't necessarily correspond to the spectral type requested.

In [393]: spt2[0]
Out[393]: 'T7.5'

In [390]: test = splat.getSpectrum(optspt=spt2[0], lucky=True, binary=False, spbinary=False, giant=False, subdwarf=False)[0]

Retrieving 1 lucky file

In [392]: test[0].plot()

(A spectrum that definitely doesn't look like a T dwarf)

In [395]: splat.classifyByStandard(test[0])
Out[395]: ('L6.0', 0.5)

**Comment by aburgasser** [comment]
it was, now fixed!
