### ISSUE TITLE
background source with no SpT result from getSpectrum

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#77]
In [1]: nirspc = splat.getSpectrum(nirspt=['L9','T9'], binary=False, spbinary=False, giant=False, subdwarf=False)

In[2]: nirspecdf['spectra'][30]
Out[2]: SPEX_PRISM spectrum of J0330-0000 Background Source

In[3]: nirspecdf['spectra'][30].spex_type,nirspecdf['spectra'][30].opt_type,nirspecdf['spectra'][30].nir_type, nirspecdf['spectra'][30].lit_type
Out[3]: ('--', '--', 'giant?', '--')

So how did this get retrieved in the first place?

**Comment by aburgasser** [comment]
error in catalog - now fixed
