### ISSUE TITLE
what is this called now? splat.SPEX_STDS['M5']

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#78]
splat.initiateStandards()
splat.SPEX_STDS['M5']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-93-b1edfc8ffba9> in <module>()
----> 1 splat.SPEX_STDS['M5']

AttributeError: module 'splat' has no attribute 'SPEX_STDS'

**Comment by aburgasser** [comment]
it is splat.STDS_DWARF_SPEX['M5.0']. Note you should initialize standards before using this in this manner.
