### ISSUE TITLE
simulateAges 'just' and 'just_exponential' distributions not working. All the other ones work OK.

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#79]
evolve.simulateAges(10,distribution='just_exponential')

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-42-a1855b6a5d78> in <module>()
----> 1 evolve.simulateAges(10,distribution='just_exponential')

/Users/daniella/Python/splat/splat/evolve.py in simulateAges(num, **kwargs)
    953         ages = numpy.max(ages)-ages
    954 
--> 955     return ages
    956 
    957 

UnboundLocalError: local variable 'ages' referenced before assignment

**Comment by aburgasser** [comment]
resolved!
