### ISSUE TITLE
classify by index for testi is giving wrong resutls

### ISSUE THREAD

**Issue by aburgasser** [aburgasser/splat#80]
I think the spectral type numbers need to by multiplied by 10

**Comment by daniellabardalezgagliuffi** [comment]
Do you mean multiply the result from the index classification from Testi 2001 such that an L0.9 would be an L9?
Is this already fixed in the new version of SPLAT? I’ll download it tomorrow.

Daniella

**Comment by aburgasser** [comment]
fixed
