### ISSUE TITLE
Model SEDs do not appear to have the correct flux values

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#81]
I was comparing the BT-Settl models that splat.model produces. Here is a comparison figure of SEDs:
![image](https://cloud.githubusercontent.com/assets/7979844/26233106/f2f41f2e-3c0f-11e7-8c49-991937f3b4f2.png)
The BT-Settl values (orange) come from the latest set of models, although I don't think that would account for the big difference in surface fluxes. Maybe I'm missing something here, like the SPLAT model is multiplied by some factor. The example above is for Teff = 1700, Logg = 5.0.

**Comment by aburgasser** [comment]
fixed - weird coded in 10**4
