### ISSUE TITLE
something wrong with vlg=True

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [aburgasser/splat#82]
While re-running the whole sample analysis code, I found that this command gave an error. It works fine for intg=True, it's only failing for vlg=True.

[In]: splat.classifyByStandard(sp,plot=True,method='kirkpatrick',vlg=True)

[Out]:
ValueError                                Traceback (most recent call last)
<ipython-input-286-a1eb203a1395> in <module>()
----> 1 splat.classifyByStandard(sp,plot=True,method='kirkpatrick',vlg=True)

/Users/daniella/Python/splat/splat/core.py in classifyByStandard(sp, *args, **kwargs)
   2933 
   2934     for t in spt_sample:
-> 2935         chisq,scale = compareSpectra(sp,stds[typeToNum(t,subclass=subclass)],fit_ranges=fit_ranges,statistic=statistic,novar2=True)
   2936         stat.append(chisq)
   2937         sspt.append(t)

/Users/daniella/Python/splat/splat/core.py in compareSpectra(sp1, sp2, *args, **kwargs)
   3523 
   3524 # create interpolation function for second spectrum
-> 3525     f = interp1d(sp2.wave,sp2.flux,bounds_error=False,fill_value=0.)
   3526     if var_flag:
   3527         v = interp1d(sp2.wave,sp2.variance*numpy.nan,bounds_error=False,fill_value=numpy.nan)

/Users/daniella/miniconda3/lib/python3.5/site-packages/scipy/interpolate/interpolate.py in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
    444         # Interpolation goes internally along the first axis
    445         self.y = y
--> 446         self._y = self._reshape_yi(self.y)
    447         self.x = x
    448         del y, x  # clean up namespace to prevent misuse; use attributes

/Users/daniella/miniconda3/lib/python3.5/site-packages/scipy/interpolate/polyint.py in _reshape_yi(self, yi, check)
    109                                            self._y_extra_shape[:-self._y_axis])
    110             raise ValueError("Data must be of shape %s" % ok_shape)
--> 111         return yi.reshape((yi.shape[0], -1))
    112 
    113     def _set_yi(self, yi, xi=None, axis=None):

ValueError: cannot reshape array of size 0 into shape (0,newaxis)

**Comment by aburgasser** [comment]
fixed
