### ISSUE TITLE
Need 'rsr' keyword to be defined for all filters in initialize.py

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#83]
filterMag is throwing the following error (on sdss bandpasses):
`rsr = kwargs.get('rsr',FILTERS[filt]['rsr'])`

I identified the issue being the 'rsr' keyword isn't set under FILTERS in intialize.py for the SDSS bandpasses. Probably should add this keyword to all the filters.

**Comment by aburgasser** [comment]
fixed
