### ISSUE TITLE
Recommend tighter plotting for publications

### ISSUE THREAD

**Issue by ctheissen** [aburgasser/splat#84]
I recommend changing line 697 in `plot.py` from
`plt.savefig(files[plts], format=filetype)`
to `plt.savefig(files[plts], format=filetype, bbox_inches='tight')`.
This will remove the whitespace around the figure before it is created. It makes for tighter plots in the publication.

**Comment by aburgasser** [comment]
done - there is now a "tight" option on both plotSpectrum and plotMap, defaults to True
