### ISSUE TITLE
Empty Spectra & normalization

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#86]
There should probably be a self.isEmpty in the Spectrum object for empty spectra (flux= np.nan or zeros). This issue has come up when trying to normalize an empty spectrum (without knowing it was empty). I get the following error
 
File "/Users/caganze/Research/splat/splat/core.py", line 1073, in normalize
    self.scale(1./self.fluxMax(**kwargs).value,silent=True)
ZeroDivisionError: float division by zero

**Comment by aburgasser** [comment]
i've fixed this so it will allow you to hang yourself - it will give a warning but not crash. Good luck!
