### ISSUE TITLE
plot.py: Highlighting specific bands while plotting a spectral sequence

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#87]
I probably missed this, but there is no option to highlight a chosen band (not a predefined molecular absorption feature or telluric bands). It would be very helpful

**Comment by aburgasser** [comment]
this wasn't there, so now it is added in plotSpectrum - the following optional parameters:

    band(s) = []
        a single or array of 2-element arrays that indicate bands that you want to specifically shade in
    bandcolor(s) = []
        a single or array of colors to shade the bands (default = 'k')
    bandalpha(s) = []
        a single or array of alphas to shade the bands (default = 0.2)
    bandlabel(s) = []
        a single or array of labels to annotate the bands (default = '')
    bandlabelposition(s) = []
        a single or array of strings indicating the position of the labels; can be 'bottom', 'middle', or 'top' (default = 'bottom')

here's an example of it in use:

import splat.plot as splot
spl = splat.getSpectrum(shortname='1047+2124')[0]
spl.plot(bands=[[1.2,1.3],[1.6,1.8]],bandcolors=['r','g'],bandalpha=0.2,bandlabels=['index1','index2'],bandlabelposition='top')
<img width="572" alt="screen shot 2017-06-28 at 5 52 51 pm" src="https://user-images.githubusercontent.com/5667900/27666714-aa34929c-5c2a-11e7-88e1-74163987f4fc.png">
