### ISSUE TITLE
Issue getting subdwarf spectra

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#88]
I ran these two lines 
`db=splat.core.searchLibrary(spt=[15,39],  subdwarf=True)['DATA_FILE'] 
spectra=[splat.core.Spectrum(x) for x in db.data]`

I get this error message  (on line 276 )
 File "/Users/caganze/Research/splat/splat/core.py", line 276, in __init__
    if sdb != False:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

it seems like sdb is an array not a bool

**Comment by aburgasser** [comment]
this was an error based on the presence of a redundant listing in db_spectrum; cleaned and a better test used at this step
