### ISSUE TITLE
compareSpectra vs ClassifyByStandard

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#89]
I have a spectrum that looks like an late m-dwarf but classify by standard returns T9 as the classification 

spt=splat.classifyByStandard(spl, showNoise=True,fit_ranges=[[1.2, 1.3]], mask=[1.6, 1.7],plot=True, xrange=[1.1, 1.7], verbose=True) 

but this looks like a late M dwarfs

m8=splat.getStandard('M7')
splat.compareSpectra(m8, spl,xrange=[1.1, 1.7], fit_ranges=[[1.2, 1.6]], plot=True )

![fig1](https://user-images.githubusercontent.com/7990189/27665627-16b02c04-5c23-11e7-973e-eb13128a1249.png)
![fig2](https://user-images.githubusercontent.com/7990189/27665626-16aea9f6-5c23-11e7-80d6-bc0ae04311f0.png)
Same problem with a t-dwarf
![fig3](https://user-images.githubusercontent.com/7990189/27665653-37b40ca4-5c23-11e7-902c-f0879bbd6087.png)

**Comment by aburgasser** [comment]
I'm having trouble reproducing this; here's the commands I used for your file:

file = '/Users/adam/projects/splat/testing/Par32_BEAM_79A.dat'
spl = splat.Spectrum(file,wunit=u.Angstrom)
spl.toMicron()
spl.plot()
spt=splat.classifyByStandard(spl, showNoise=True,fit_ranges=[[1.2, 1.3]], mask=[1.6, 1.7],plot=True, xrange=[1.1, 1.7], verbose=True)

**Comment by aburgasser** [comment]
issue resolved in Christian's side
