### ISSUE TITLE
Issue with searchLibrary logic

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#91]
`splat.getSpectrum(spt=[15, 39], subdwarf=False, wd=False)`
Returns 27 files that are all giants, should it be returning the opposite ?

**Comment by caganze** [comment]
> `splat.searchLibrary(spt=[15,39],subdwarf=False, giant=False) `
works as intended (2125 entries)

> `splat.searchLibrary(spt=[15,39], subdwarf=False, wd=False)`
returns 27 entries

> `splat.searchLibrary(spt=[15, 39], subdwarf=False, wd=False, giant=False)`
returns 5 entries

**Comment by aburgasser** [comment]
fixed!
