### ISSUE TITLE
Issue with getSpectrum

### ISSUE THREAD

**Issue by dorsa-pearl** [aburgasser/splat#93]
> `sp=splat.getSpectrum(lucky=True)`

> `sp.plot()`

returns 

C:\Users\dm_do\Desktop\Python\splat\splat\core.py in getSpectrum(*args, **kwargs)
   1621     if len(search) > 0:
   1622         files = []
-> 1623         for i,x in enumerate(search['DATA_KEY']):
   1624             files.append(str(search['DATA_KEY'][i])+'_'+str(search['SOURCE_KEY'][i])+'.fits')
   1625 

TypeError: 'numpy.int32' object is not iterable

**Comment by aburgasser** [comment]
I think this is now all fixed - there were some deep bugs that needed squashing and we just converted databases to pandas; may be unstable so let me know if problems arise
