### ISSUE TITLE
Issue with Importing splat

### ISSUE THREAD

**Issue by caganze** [aburgasser/splat#94]
I just installed splat on a new computer
`import splat` 
returns an error (An issue with astropy units). 
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7b0da159df16> in <module>()
----> 1 import splat

/Users/aganze/splat/splat/__init__.py in <module>()
      5 from __future__ import absolute_import, division, print_function, unicode_literals
      6 
----> 7 from .core import *
      8 from .initialize import *
      9 from .utilities import *

/Users/aganze/splat/splat/core.py in <module>()
     50 
     51 # splat functions and constants
---> 52 from splat.initialize import *
     53 from splat.utilities import *
     54 import splat.citations as spbib

/Users/aganze/splat/splat/initialize.py in <module>()
    342 SPECTRAL_MODEL_PARAMETERS = {\
    343     'teff': {'prefix': 't', 'unit': u.K, 'default': 1000.0, 'title': '$T_{eff}$', 'type': 'continuous'}, \
--> 344     'logg': {'prefix': 'g', 'unit': u.dex(), 'default': 5.0, 'title': '$\log{g}$', 'type': 'continuous'}, \
    345     'z': {'prefix': 'z', 'unit': u.dex(), 'default': 0., 'title': '$[M/H]$', 'type': 'continuous'}, \
    346     'fsed': {'prefix': 'f', 'unit': u.m/u.m, 'default': 'nc', 'title': '$f_{sed}$', 'type': 'discrete'}, \

TypeError: 'IrreducibleUnit' object is not callable

**Comment by aburgasser** [comment]
I think this may the result of an outdated astropy, but i've changed the u.dex() to u.dex to make sure it doesn't barf. please verify that it works on your end (works on mine)

**Comment by aburgasser** [comment]
This turned
